#!/usr/bin/env bash
#
# Generate spkr_test/src/clip_pcm.h from a spoken sentence, using only
# macOS-native tools (say + afconvert + python3). Output is 16 kHz mono 16-bit
# PCM embedded as a C array, for the speaker intelligibility test.
#
# Usage:  ./make_clip_header.sh ["sentence to speak"]
# (no arg -> uses the default intelligibility-stress sentence below)
#
set -euo pipefail

DEFAULT="Your next meeting is at three fifteen. It's sixty-eight degrees and sunny, with a slight chance of showers near six."
SENTENCE="${1:-$DEFAULT}"

HERE="$(cd "$(dirname "$0")/.." && pwd)"   # spkr_test/
OUT="$HERE/src/clip_pcm.h"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

say -o "$TMP/clip.aiff" "$SENTENCE"
afconvert -f WAVE -d LEI16@16000 -c 1 "$TMP/clip.aiff" "$TMP/clip.wav"

python3 - "$TMP/clip.wav" "$OUT" "$SENTENCE" <<'PY'
import sys, wave, struct
wav_path, out_path, sentence = sys.argv[1], sys.argv[2], sys.argv[3]
w = wave.open(wav_path, 'rb')
assert w.getsampwidth() == 2 and w.getnchannels() == 1, "expected 16-bit mono"
n = w.getnframes()
samples = struct.unpack('<%dh' % n, w.readframes(n))
w.close()
with open(out_path, 'w') as f:
    f.write('/* Auto-generated by tools/make_clip_header.sh -- DO NOT EDIT BY HAND.\n')
    f.write(' * 16 kHz mono 16-bit PCM TTS clip for the speaker intelligibility test.\n')
    f.write(' * Sentence: "%s"\n */\n' % sentence.strip())
    f.write('#pragma once\n#include <stdint.h>\n\n')
    f.write('#define CLIP_PCM_RATE 16000\n')
    f.write('#define CLIP_PCM_LEN  %d\n\n' % n)
    f.write('static const int16_t clip_pcm[CLIP_PCM_LEN] = {\n')
    for i in range(0, n, 12):
        f.write('\t' + ','.join('%d' % s for s in samples[i:i+12]) + ',\n')
    f.write('};\n')
print("wrote %s : %d samples, %.2f s, %d KB" % (out_path, n, n/16000.0, n*2//1024))
PY
